import{BadRequestException,ConflictException,Inject,Injectable,NotFoundException}from'@nestjs/common';import{HttpService}from'@nestjs/axios';import{InjectRepository}from'@nestjs/typeorm';import{ClientProxy}from'@nestjs/microservices';import{firstValueFrom}from'rxjs';import{Repository}from'typeorm';import{CreateOrderDto}from'./dto';import{Order,OrderStatus}from'./order.entity';
@Injectable()export class OrderService{constructor(@InjectRepository(Order)private readonly repo:Repository<Order>,private readonly http:HttpService,@Inject('PAYMENT_BUS')private readonly payments:ClientProxy,@Inject('NOTIFICATION_BUS')private readonly notifications:ClientProxy){}
 async create(dto:CreateOrderDto,key:string,authorization?:string){if(!key)throw new BadRequestException('Idempotency-Key header is required');const existing=await this.repo.findOneBy({idempotencyKey:key});if(existing)return existing;
  const items=[] as any[];for(const item of dto.items){const product=(await firstValueFrom(this.http.get(`${process.env.PRODUCT_SERVICE_URL??'http://product-service:3002'}/api/v1/products/${item.product_id}`,{headers:{authorization}}))).data;await firstValueFrom(this.http.post(`${process.env.PRODUCT_SERVICE_URL??'http://product-service:3002'}/api/v1/products/${item.product_id}/reservations`,{quantity:item.quantity},{headers:{authorization}}));items.push({...item,unit_price:product.price});}
  const total=items.reduce((s,i)=>s+i.unit_price*i.quantity,0);const order=await this.repo.save(this.repo.create({customerId:dto.customer_id,items,totalAmount:total,currency:dto.currency,status:'PENDING',idempotencyKey:key}));const event={order_id:order.id,customer_id:order.customerId,amount:Number(order.totalAmount),currency:order.currency,items:order.items};this.payments.emit('order.created',event);this.notifications.emit('order.created',event);return order;}
 async findOne(id:string){const x=await this.repo.findOneBy({id});if(!x)throw new NotFoundException('Order not found');return x;}
 findByUser(userId:string){return this.repo.find({where:{customerId:userId},order:{createdAt:'DESC'}})}
 async transition(id:string,next:OrderStatus){const order=await this.findOne(id);if(order.status===next)return order;const allowed:Record<OrderStatus,OrderStatus[]>={PENDING:['CONFIRMED','CANCELLED'],CONFIRMED:['PROCESSING','CANCELLED'],PROCESSING:['SHIPPED','CANCELLED'],SHIPPED:['DELIVERED'],DELIVERED:[],CANCELLED:[]};if(!allowed[order.status].includes(next))throw new ConflictException(`Invalid transition ${order.status} -> ${next}`);order.status=next;const saved=await this.repo.save(order);this.notifications.emit(`order.${next.toLowerCase()}`,{order_id:id,customer_id:order.customerId,status:next});return saved;}
}
