import { BadRequestException, Injectable, NotFoundException, OnModuleInit } from '@nestjs/common'; import { Client } from '@elastic/elasticsearch'; import { randomUUID } from 'crypto'; import { CreateProductDto, ListProductsDto, SearchDto, UpdateProductDto } from './dto';
@Injectable() export class ProductService implements OnModuleInit {
  private readonly index='products'; private readonly es=new Client({node:process.env.ELASTICSEARCH_URL??'http://elasticsearch:9200'});
  async onModuleInit(){ if(!(await this.es.indices.exists({index:this.index}))) await this.es.indices.create({index:this.index,mappings:{properties:{name:{type:'text'},sku:{type:'keyword'},category:{properties:{id:{type:'integer'},name:{type:'keyword'}}},price:{type:'double'},currency:{type:'keyword'},stock:{type:'integer'},deleted:{type:'boolean'},created_at:{type:'date'},updated_at:{type:'date'}}}}); }
  async create(dto:CreateProductDto){const id=randomUUID(),now=new Date().toISOString();const product={id,...dto,rating:0,review_count:0,deleted:false,created_at:now,updated_at:now};await this.es.index({index:this.index,id,document:product,refresh:true});return product;}
  async findOne(id:string){try{const r=await this.es.get({index:this.index,id});const p=r._source as any;if(p.deleted) throw new Error();return p;}catch{throw new NotFoundException('Product not found');}}
  private filters(q:ListProductsDto){const f:any[]=[{term:{deleted:false}}];if(q.category)f.push({term:{'category.name':q.category}});if(q.min_price!==undefined||q.max_price!==undefined)f.push({range:{price:{gte:q.min_price,lte:q.max_price}}});return f;}
  async list(q:ListProductsDto,search?:string){const from=(q.page-1)*q.limit;const result=await this.es.search({index:this.index,from,size:q.limit,query:search?{bool:{must:[{multi_match:{query:search,fields:['name^3','sku','category.name']}}],filter:this.filters(q)}}:{bool:{filter:this.filters(q)}},sort:q.sort==='created_at'?[{created_at:q.order}]:[{[q.sort]:q.order}]});const total=typeof result.hits.total==='number'?result.hits.total:result.hits.total?.value??0;return{data:result.hits.hits.map(h=>h._source),pagination:{page:q.page,limit:q.limit,total,total_pages:Math.ceil(total/q.limit)}};}
  search(q:SearchDto){return this.list(q,q.q);}
  async update(id:string,dto:UpdateProductDto){await this.findOne(id);await this.es.update({index:this.index,id,doc:{...dto,updated_at:new Date().toISOString()},refresh:true});return this.findOne(id);}
  async remove(id:string){await this.findOne(id);await this.es.update({index:this.index,id,doc:{deleted:true,updated_at:new Date().toISOString()},refresh:true});}
  async reserve(id:string,quantity:number){const p:any=await this.findOne(id);if(p.stock<quantity)throw new BadRequestException({code:'STOCK_NOT_AVAILABLE',product_id:id,available:p.stock,requested:quantity});await this.es.update({index:this.index,id,script:{source:'ctx._source.stock -= params.qty; ctx._source.updated_at = params.now',params:{qty:quantity,now:new Date().toISOString()}},refresh:true});return{product_id:id,reserved:quantity,remaining:p.stock-quantity};}
}
